import { CMS_NAME } from "@/lib/constants";
import { BLOG_TITLE } from "@/lib/constants";

export function Intro() {
  return (
    <><section className="flex-col md:flex-row flex items-center md:justify-between mt-16 mb-16 md:mb-12">
      <h2 className="text-xl md:text-3xl font-bold tracking-tighter leading-tight md:pr-8">
        ⚠️ Disclaimer: This content is generated by AI 🤖
      </h2>
    </section><section className="flex-col md:flex-row flex items-center md:justify-between mt-16 mb-16 md:mb-12">
        <h1 className="text-5xl md:text-8xl font-bold tracking-tighter leading-tight md:pr-8">
          {BLOG_TITLE}
        </h1>
      </section></>
  );
}
